project: 
  type: website
  
website: 
  title: "Bayes Para Entender la Obesidad - De datos clínicos a decisiones bajo incertidumbre"
  favicon: favicon.ico
  sidebar: 
    style: "docked"
    contents: 
      - index.qmd
      # Nota: los comentarios van después de la almohadilla o numeral 
      - analysis/c00-prefacio.qmd
      - section: "Módulo 1: Pensar Como Analista Bayesiano"
        #href: analysis/m01.qmd
        contents: 
        - analysis/c01.qmd
        - analysis/c02.qmd
      - section: "Módulo 2: Herramientas en R (mínimo necesario)"
        #href: analysis/m02.qmd
        contents: 
        - analysis/c03.qmd
        - analysis/c04.qmd
      - section: "Módulo 3: Entender la Incertidumbre"
        #href: analysis/m03.qmd
        contents:
        - analysis/c05.qmd
        - analysis/c06.qmd
        - analysis/c07.qmd
      - section: "Módulo 4: Pensamiento causal"
        #href: analysis/m04.qmd
        contents:
        - analysis/c08.qmd
        - analysis/c09.qmd
        - analysis/c10.qmd
  page-footer: 
    border: false
    background: light
    center: "Copyright, David Villafuerte MD." 
    left: 
      - icon: github
        href: https://github.com/
      - icon: bluesky 
        href: https://bsky.app/ 
    
format: 
  html: 
    theme: cosmo
    toc: true